# Generated by Django 3.2 on 2023-01-12 10:27

from django.db import migrations


def forwards_func(apps, schema_editor):
    News = apps.get_model("mainapp", "News")
    News.objects.create(title="some title", body="some body")


def reverse_func(apps, schema_editor):
    News = apps.get_model("mainapp", "News")
    News.objects.all().order_by("-id").first().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
